// Layer 6: Automation Layer - Threshold Policies

export const AUTOMATION_THRESHOLDS = {
  DEFAULT_MAX_ATTEMPTS: 3,
  MAX_JOBS_IN_QUEUE: 100,
  MAX_AUDIT_LOG_ENTRIES: 1000,
  IDEMPOTENCY_KEY_TTL_HOURS: 24,
  WORKER_POLL_INTERVAL_MS: 1000
};
